// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlhx2RmYh5s80C7DnvGdXaaNZ5Gwfu2QY',
    appId: '1:65209678350:web:497210ce76b694ea221a5f',
    messagingSenderId: '65209678350',
    projectId: 'asian-cable-fiber',
    authDomain: 'asian-cable-fiber.firebaseapp.com',
    storageBucket: 'asian-cable-fiber.firebasestorage.app',
    measurementId: 'G-8E3B70R7ND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo3dDApXc51CiSlvCz3RmIMQkzLxmF2jw',
    appId: '1:65209678350:android:bb34b3d07c20d3e7221a5f',
    messagingSenderId: '65209678350',
    projectId: 'asian-cable-fiber',
    storageBucket: 'asian-cable-fiber.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKd7E50Ivu-N9Xqc9AjdmBs-Vs7cu5B7U',
    appId: '1:65209678350:ios:6573319b7eb234f0221a5f',
    messagingSenderId: '65209678350',
    projectId: 'asian-cable-fiber',
    storageBucket: 'asian-cable-fiber.firebasestorage.app',
    iosBundleId: 'com.example.asianCableFiber',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKd7E50Ivu-N9Xqc9AjdmBs-Vs7cu5B7U',
    appId: '1:65209678350:ios:6573319b7eb234f0221a5f',
    messagingSenderId: '65209678350',
    projectId: 'asian-cable-fiber',
    storageBucket: 'asian-cable-fiber.firebasestorage.app',
    iosBundleId: 'com.example.asianCableFiber',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlhx2RmYh5s80C7DnvGdXaaNZ5Gwfu2QY',
    appId: '1:65209678350:web:1248198ec666ce24221a5f',
    messagingSenderId: '65209678350',
    projectId: 'asian-cable-fiber',
    authDomain: 'asian-cable-fiber.firebaseapp.com',
    storageBucket: 'asian-cable-fiber.firebasestorage.app',
    measurementId: 'G-EG0PDY7XNV',
  );
}
